= サブネットマッピング
:allow-uri-read: 




=== サブネットマッピング

このリリースでは、サブネットマッピングを使用してフェイルオーバー時のIPアドレスを新しい方法で管理できます。これにより、各vCenterにサブネットを追加できます。その場合は、IPv4 CIDR、デフォルトゲートウェイ、および各仮想ネットワークのDNSを定義します。

フェイルオーバー時に、BlueXP  ディザスタリカバリは、マッピングされた仮想ネットワーク用に提供されたCIDRを参照して、各vNICの適切なIPアドレスを決定し、それを使用して新しいIPアドレスを取得します。

例：

* networkA = 10.1.1.0/24
* ネットワークB = 192.168.1.0/24


VM1には、NetworkAに接続されたvNIC（10.1.1.50）があります。NetworkAは、レプリケーションプラン設定でNetworkBにマッピングされます。

フェイルオーバー時、BlueXP  ディザスタリカバリは元のIPアドレス（10.1.1）のネットワーク部分を置き換え、元のIPアドレス（10.1.1.50）のホストアドレス（.50）を維持します。VM1の場合、BlueXP  ディザスタリカバリは、NetworkBのCIDR設定を確認し、ホスト部分（.50）を維持しながら、NetworkBネットワーク部分192.168.1を使用してVM1の新しいIPアドレスを作成します。新しいIPは192.168.1.50になります。

つまり、ホストアドレスは同じままですが、ネットワークアドレスはサイトサブネットマッピングで設定されているものに置き換えられます。これにより、フェイルオーバー時のIPアドレスの再割り当てをより簡単に管理できます。特に、数百のネットワークと数千のVMを管理する必要がある場合に便利です。

サイトにサブネットマッピングを含める方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenterサーバサイトを追加"]。



=== 保護をスキップ

レプリケーションプランのフェイルオーバー後にサービスが逆保護関係を自動的に作成しないように、保護をスキップできるようになりました。これは、BlueXP  ディザスタリカバリでリストアしたサイトをオンラインに戻す前に、そのサイトで追加の処理を実行する場合に便利です。

フェイルオーバーを開始すると、デフォルトでは、元のソースサイトがオンラインの場合、レプリケーションプランの各ボリュームに対して逆保護関係が自動的に作成されます。これは、サービスがターゲットサイトからソースサイトへのSnapMirror関係を作成することを意味します。フェイルバックを開始すると、SnapMirror関係も自動的に反転されます。

フェイルオーバーを開始するときに、*[Skip protection]*オプションを選択できるようになりました。これにより、サービスはSnapMirror関係を自動的に反転しません。代わりに、書き込み可能なボリュームはレプリケーション計画の両側に残ります。

元のソースサイトがオンラインに戻ったら、レプリケーションプランの[アクション]メニューから*[リソースの保護]*を選択して、逆保護を設定できます。これにより、プラン内の各ボリュームに対して逆レプリケーション関係の作成が試行されます。保護が回復するまで、このジョブを繰り返し実行できます。保護が復元されたら、通常の方法でフェイルバックを開始できます。

保護のスキップの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのVREアプリケーションの障害"]。



=== SnapMirrorスケジュールによるレプリケーション計画の更新

BlueXP  ディザスタリカバリでは、標準のONTAP SnapMirrorポリシースケジューラやONTAPとのサードパーティ統合など、外部のSnapshot管理ソリューションの使用がサポートされるようになりました。レプリケーションプラン内のすべてのデータストア（ボリューム）にすでに別の場所で管理されているSnapMirror関係がある場合は、それらのSnapshotをBlueXP  ディザスタリカバリのリカバリポイントとして使用できます。

設定するには、[Replication plan]>[Resource mapping]セクションで、データストアマッピングの設定時に*[Use platform managed backups and retention schedules]*チェックボックスをオンにします。

このオプションを選択すると、BlueXP  ディザスタリカバリでバックアップスケジュールが設定されません。ただし、テスト、フェイルオーバー、フェイルバック操作のためにスナップショットが作成される可能性があるため、保持スケジュールを設定する必要があります。

この設定後、サービスは定期的にスケジュールされたスナップショットを作成せず、代わりに外部エンティティに依存してこれらのスナップショットを作成および更新します。

保護のスキップの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。
