---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Amazon EVS と Amazon FSx for NetApp ONTAP を使用した BlueXP ディザスタリカバリのご紹介。BlueXPディザスタリカバリはライセンス製品であり、ご利用いただくにはご購入が必要です。ライセンスには複数の種類があり、購入方法も複数あります。 
---
= Amazon EVS の BlueXP アカウントに BlueXP 災害復旧サービスを追加します
:allow-uri-read: 


[role="lead"]
BlueXP ディザスタリカバリはライセンス製品であり、ご利用いただくにはご購入が必要です。ライセンスには複数の種類があり、購入方法も複数あります。ライセンスにより、一定期間、一定量のデータを保護できます。

BlueXP災害復旧ライセンスの詳細については、以下を参照してください。 link:../get-started/dr-licensing.html["BlueXPディザスタリカバリのライセンスを設定"] 。



== ライセンスの種類

ライセンスには主に 2 つの種類があります。

* NetAppはlink:../get-started/dr-licensing.html["30日間試用ライセンス"] ONTAPおよびVMwareリソースを使用してBlueXPのディザスタリカバリを評価するために使用できます。このライセンスでは、保護された容量を無制限に30日間ご利用いただけます。
* 30日間の試用期間後もDR保護をご利用になる場合は、本番環境向けライセンスをご購入ください。このライセンスは、NetAppのクラウドパートナーのマーケットプレイスからご購入いただけますが、このガイドでは、Amazon AWS MarketplaceからBlueXPディザスタリカバリ用の*NetApp Intelligent Services*ライセンスをご購入いただくことをお勧めします。AmazonMarketplaceでのライセンス購入の詳細については、こちらをご覧ください。 link:../get-started/dr-licensing.html["AWS Marketplaceでサブスクライブ"] 。




== 災害復旧能力のニーズを測る

ライセンスを購入する前に、保護する必要があるONTAPストレージ容量を把握しておく必要があります。NetAppONTAPストレージを使用するメリットの一つは、NetAppがデータを保存する際の効率性の高さです。VMwareデータストアをホストするVMwareなど、ONTAPボリュームに保存されるすべてのデータは、非常に効率的に保存されます。ONTAPは、物理ストレージにデータを書き込む際に、コンパクション、重複排除、圧縮の3種類のストレージ効率をデフォルトで設定します結果として、保存されるデータのタイプに応じて、1.5:1から4:1のストレージ効率が得られます。実際、NetAppは https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["ストレージ容量削減保証"^]特定のワークロード向け。

BlueXPディザスタリカバリは、ONTAPのすべてのストレージ効率を適用した後に、ライセンス取得のための容量を計算するため、これは大きなメリットとなります。例えば、vCenter内で100テラバイト（TiB）のNFSデータストアをプロビジョニングし、このサービスを使用して保護する100台のVMをホストしているとします。さらに、データがONTAPボリュームに書き込まれる際に、自動的に適用されるストレージ効率化技術により、これらのVMの消費量はわずか33TiB（3:1のストレージ効率）であると仮定します。BlueXPディザスタリカバリのライセンスは100TiBではなく33TiB単位で取得できます。これは、他のDRソリューションと比較して、DRソリューションの総所有コスト（TCO）を大幅に削減できるメリットとなります。

.手順
. 保護対象の VMware データストアをホストしている各ボリュームで消費されているデータ量を確認するには、各ボリュームに対して ONTAP CLI コマンドを実行して、ディスク上の容量消費量を確認します。  `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` 。
+
例：

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. 各ボリュームの*Total Physical Used*の値に注意してください。これはBlueXPディザスタリカバリで保護する必要があるデータ量であり、必要なライセンス容量を決定する際に使用する値です。

