---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Amazon EVS と Amazon FSx for NetApp ONTAP を使用した BlueXP 災害復旧の紹介。 
---
= Amazon Elastic VMware Service と Amazon FSx for NetApp ONTAP を使用した BlueXP 災害復旧の紹介
:allow-uri-read: 


[role="lead"]
お客様は、VMware vSphere ベースの仮想化インフラストラクチャなど、本番環境のコンピューティングワークロードにおいて、ますます仮想化インフラストラクチャへの依存度を高めています。これらの仮想マシン（VM）がビジネスにとってより重要になるにつれ、お客様はこれらのVMを物理コンピューティングリソースと同様の災害から保護する必要があります。現在提供されているディザスタリカバリ（DR）ソリューションは複雑で高価であり、多くのリソースを必要とします。仮想化インフラストラクチャ向けストレージプロバイダーとして最大手のNetAppは、ONTAPストレージでホストされるあらゆる種類のデータを保護するのと同様に、お客様のVMを確実に保護することに強い関心を持っています。この目標を達成するために、NetAppはBlueXPディザスタリカバリサービスを開発しました。


NOTE: この Amazon EVS に関するドキュメントは、テクノロジープレビューとして提供されています。このプレビューサービスでは、NetAppは、一般提供前にサービスの詳細、内容、スケジュールを変更する権利を留保します。

あらゆるDRソリューションにおける主要な課題の一つは、DRレプリケーションおよびリカバリインフラを提供するためだけに、追加のコンピューティング、ネットワーク、ストレージリソースの購入、構成、維持にかかる増分コストを管理することです。オンプレミスの重要な仮想リソースを保護するための一般的な選択肢の一つは、クラウドホスト型の仮想リソースをDRレプリケーションおよびリカバリインフラとして使用することです。Amazonは、NetApp ONTAPホスト型VMインフラと互換性のある費用対効果の高いリソースを提供できる、こうしたソリューションの一例です。

Amazonは、仮想プライベートクラウド（VPC）内でVMware Cloud Foundationを利用できるAmazon Elastic VMware Service（Amazon EVS）を発表しました。AmazonEVSは、AWSの耐障害性とパフォーマンスに加え、使い慣れたVMwareソフトウェアとツールを提供することで、Amazon EVS vCenterをオンプレミスの仮想化インフラストラクチャの拡張機能として統合することを可能にします。

Amazon EVS にはストレージリソースが付属していますが、ネイティブストレージを使用すると、ストレージ負荷の高いワークロードを抱える組織ではその効果が低下する可能性があります。このような場合、Amazon EVS と Amazon FSx for NetApp ONTAP ストレージ (Amazon FSxN) を組み合わせるさらに、オンプレミスで NetApp ONTAP ストレージソリューションを使用して VMware インフラストラクチャをホストしている場合、Amazon EVS と FSx for ONTAP を組み合わせることで、オンプレミスとクラウドホストのインフラストラクチャ間でクラス最高のデータ相互運用性と保護機能を実現できます。

Amazon FSx for NetApp ONTAPの詳細については、を参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSX for NetApp ONTAP の利用を開始する"^]。
