---
sidebar: sidebar 
permalink: reference/vcenter-privileges.html 
keywords: disaster recovery, bluexp, vcenter, 
summary: BlueXPのディザスタリカバリでvCenterアカウントのサービス（データストアの登録と登録解除、VMの起動と停止、仮想マシン（VM）の再設定など）を実行するには、vCenterアカウントに最小限のvCenter権限が必要です。次の表に、BlueXPディザスタリカバリをvCenterクラスタと連携させるために必要なすべての権限を示します。 
---
= BlueXPのディザスタリカバリに必要なvCenter権限
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
BlueXPのディザスタリカバリでvCenterアカウントのサービス（データストアの登録と登録解除、VMの起動と停止、仮想マシン（VM）の再設定など）を実行するには、vCenterアカウントに最小限のvCenter権限が必要です。次の表に、BlueXPディザスタリカバリをvCenterクラスタと連携させるために必要なすべての権限を示します。

[cols="25,35a,40a"]
|===
| タイプ | 権限の名前 | 説明 


| *データストア*  a| 
データストア： データストアの設定
 a| 
データストアの設定に使用します。



|   a| 
データストア： データストアの削除
 a| 
データストアを削除するには、を使用します。



| *仮想マシン*  a| 
仮想マシン。構成。設定の変更
 a| 
一般的なVM設定を変更する場合に使用します。



|   a| 
仮想マシン。構成。デバイス設定の変更
 a| 
既存のデバイスのプロパティを変更する場合に使用します。



|   a| 
Virtual Machine.Configuration.Reload from path（仮想マシン構成パスから再ロード）
 a| 
VMのIDを保持しながらVM設定パッチを変更する場合に使用します。VMware vCenter Site Recovery Managerなどのソリューションでは、この操作を使用して、フェイルオーバーおよびフェイルバック時にVMの識別を維持します。



|   a| 
virtual machine.Configuration.Rename
 a| 
VMの名前を変更したり、VMに関連付けられているノードを変更したりする場合に使用します。



|   a| 
仮想マシン構成ゲスト情報のリセット
 a| 
VMのゲストオペレーティングシステム情報を編集する場合に使用します。



|   a| 
仮想マシン。構成。メモリの変更
 a| 
VMに割り当てられているメモリ容量を変更する場合に使用します。



|   a| 
仮想マシン。構成。CPU数の変更
 a| 
仮想CPUの数を変更する場合に使用します。



| *仮想マシンゲスト*  a| 
仮想マシン： ゲスト操作。 ゲスト操作の変更
 a| 
VMのゲストオペレーティングシステムに対する変更（VMへのファイルの転送など）を含むVMゲスト処理を有効にします。



| *仮想マシンの操作*  a| 
仮想マシン.Interaction.Power Off
 a| 
電源がオンになっているVMの電源をオフにする場合に使用します。この操作により、ゲストOSの電源がオフになります。



|   a| 
仮想マシン.Interaction.Power On
 a| 
電源がオフになっているVMの電源をオンにし、一時停止中のVMを再開する場合に使用します。



|   a| 
仮想マシン.Interaction.VMware Toolsのインストール
 a| 
VMware Tools CDインストーラをゲストOSのCD-ROMとしてマウントおよびアンマウントする場合に使用します。



| *仮想マシンインベントリ*  a| 
仮想マシン.インベントリ.新規作成
 a| 
VMを作成し、その実行にリソースを割り当てるために使用します。



|   a| 
仮想マシン.Inventory.Register
 a| 
vCenter Serverまたはホストインベントリに既存のVMを追加する場合に使用します。



|   a| 
仮想マシン.Inventory.Unregister
 a| 
vCenter ServerまたはホストインベントリからVMの登録を解除するために使用します。



| *仮想マシンの状態*  a| 
仮想マシン： Snapshot管理： Snapshotの作成
 a| 
VMの現在の状態からスナップショットを作成するために使用します。



|   a| 
仮想マシン： Snapshot管理： Snapshotを削除
 a| 
スナップショット履歴からスナップショットを削除する場合に使用します。



|   a| 
仮想マシン： Snapshot管理： スナップショットに戻す
 a| 
VMを特定のスナップショット時の状態に設定するために使用します。

|===