---
sidebar: sidebar 
permalink: use/dashboard-view.html 
keywords: disaster recovery remediate, disaster recovery, failover, failback, replication 
summary: NetApp BlueXPディザスタリカバリは、ディザスタリカバリのワークフローを自動化するクラウドベースのディザスタリカバリサービスです。 
---
= ダッシュボードでディザスタリカバリプランの健全性を表示する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
BlueXPディザスタリカバリダッシュボードを使用して、ディザスタリカバリサイトとレプリケーション計画の健全性を確認できます。健全なサイトとプラン、切断されているサイト、またはデグレード状態のサイトとプランを簡単に確認できます。

.手順
. BlueXPの左側のナビゲーションで、*[保護]*>*[ディザスタリカバリ]*を選択します。
. BlueXPディザスタリカバリのトップメニューで、*[ダッシュボード]*を選択します。
. ダッシュボードで次の情報を確認します。
+
** *サイト*:サイトの正常性を表示します。サイトのステータスは次のいずれかになります。
+
*** *正常*：vCenterは接続されて実行されています。
*** *切断*：vCenterに到達できないか、接続に問題があります。
*** *デグレード*：vCenterに到達できないか、接続に問題があります。
+
サイトの詳細を表示するには、ステータスについては*[すべて表示]*を選択し、すべてを表示するには*[サイトの表示]*を選択します。



** *レプリケーションプラン*:プランの正常性を表示します。計画のステータスは次のいずれかになります。
+
*** *準備完了*
*** *失敗*
+
レプリケーション計画の詳細を確認するには、ステータスの場合は*[すべて表示]*を選択し、すべてを表示するには*[レプリケーション計画の表示]*を選択します。



** *リソースグループ*:リソースグループの正常性を表示します。リソースグループのステータスは次のいずれかになります。
+
*** *保護されているVM *：VMはリソースグループの一部です。
*** *保護されていないVM *：VMはリソースグループに属していません。
+
リソースグループの詳細を確認するには、ステータスについては*[すべて表示]*を選択し、すべてを表示するには*[リソースグループを表示]*を選択します。



** フェイルオーバー、テストフェイルオーバー、および移行の数。たとえば、2つのプランを作成してデスティネーションに移行した場合、移行カウントは「2」と表示されます。


. [Activity]ペインですべての処理を確認します。ジョブモニタですべての処理を表示するには、*[すべてのジョブを表示]*を選択します。

