---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites, bluexp disaster recovery 
summary: BlueXPディザスタリカバリを使用する前に、ONTAPストレージ、VMware vCenterクラスタ、およびBlueXPの要件を環境が満たしていることを確認する必要があります。 
---
= BlueXPディザスタリカバリの前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
BlueXPディザスタリカバリを使用する前に、ONTAPストレージ、VMware vCenterクラスタ、およびBlueXPの要件を環境が満たしていることを確認する必要があります。



== ONTAPストレージの前提条件

これらの前提条件は、ONTAPまたはAmazon FSx for NetApp ONTAPのインスタンスに適用されます。

* ソースクラスタとデスティネーションクラスタのピア関係が確立されている必要があります。
* ディザスタリカバリボリュームをホストするSVMがデスティネーションクラスタに存在している必要があります。
* ソースSVMとデスティネーションSVMのピア関係が確立されている必要があります。
+

NOTE: デスティネーションSVMにディザスタリカバリボリュームを事前に作成しないでください。BlueXPディザスタリカバリでは、レプリケーション計画に必要に応じてデスティネーションボリュームが作成されます。

* Amazon FSx for NetApp ONTAPを導入する場合は、次の前提条件が適用されます。
+
** VPCには、VMware DRデータストアをホストするAmazon FSx for NetApp ONTAPインスタンスが存在している必要があります。Amazon FSx for ONTAPに関するドキュメントを参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["利用を開始するには"^]。






== VMware vCenterクラスタの前提条件

これらの前提条件は、オンプレミスのvCenterクラスタとVMware Cloud for AWS Software-Defined Data Center（SDDC）の両方に適用されます。

* BlueXPディザスタリカバリで管理するすべてのVMwareクラスタがONTAPボリュームでホストされている必要があります。
* BlueXPのディザスタリカバリで管理するすべてのVMwareデータストアでは、次のいずれかのプロトコルを使用する必要があります。
+
** NFS
** iSCSIプロトコルまたはFCプロトコルを使用するVMFS


* VMware vSphereバージョン7.0 Update 3（7.0v3）以降
* VMware Cloud SDDCを使用している場合は、次の前提条件が適用されます。
+
** VMware Cloud Consoleで、管理者とNSXクラウド管理者のサービスロールを使用します。また、組織ロールに組織オーナーを使用します。を参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["ドキュメント『Using VMware Cloud Foundations with AWS FSx for NetApp ONTAP』"^]。
** VMware Cloud SDDCとAmazon FSx for NetApp ONTAPインスタンスをリンクします。を参照してください https://vmc.techzone.vmware.com/fsx-guide#overview["VMware Cloud on AWSとAmazon FSx for NetApp ONTAPの統合の導入情報"^]。






== BlueXPの前提条件



=== BlueXPの使用を開始しましょう

まだ行っていない場合は、 https://docs.netapp.com/us-en/bluexp-setup-admin/task-sign-up-saas.html["BlueXP  にサインアップして組織を作成する"^]



=== ONTAPとVMwareのクレデンシャルを収集する

* BlueXP  ディザスタリカバリの管理に使用するBlueXP  プロジェクト内の作業環境に、Amazon FSx for ONTAPとAWSのクレデンシャルを追加する必要があります。
* BlueXPディザスタリカバリにはvCenterクレデンシャルが必要です。BlueXPディザスタリカバリでサイトを追加するときにvCenterクレデンシャルを入力します。
+
必要なvCenter権限の一覧については、を参照してください link:../reference/vcenter-privileges.html["BlueXPのディザスタリカバリに必要なvCenter権限"]。サイトの追加方法については、を参照してください link:../use/sites-add.html["サイトの追加"]。





=== BlueXPコネクタの作成

BlueXPでBlueXPコネクタがセットアップされている必要があります。BlueXP Connectorを使用すると、ディザスタリカバリサービスに適した機能が含まれます。

* BlueXPディザスタリカバリは、Standard Mode Connector環境でのみ機能します。を参照して https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html["BlueXPの標準モードでの使用"^]
* 必要なBlueXPコネクタのタイプ：
+
** *オンプレミスからオンプレミスへのディザスタリカバリ*：ディザスタリカバリサイトにBlueXP On-Premises Connectorをインストールします。を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["コネクタをオンプレミスにインストールしてセットアップします"^]。
** *オンプレミスからAWSへ*：BlueXP Connector for AWSをAWS VPCにインストールします。を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html["AWSでのコネクタのインストールオプション"^]。
+

TIP: オンプレミスからオンプレミスへの移行には、BlueXPのオンプレミスコネクタを使用します。オンプレミスからAWSへの接続には、BlueXP AWSコネクタを使用します。このコネクタは、ソースのオンプレミスvCenterとデスティネーションのオンプレミスvCenterにアクセスできます。

** インストールされているBlueXP Connectorから、BlueXPディザスタリカバリで管理するすべてのVMwareクラスタにアクセスできる必要があります。


* BlueXP  ディザスタリカバリで管理するすべてのONTAPアレイを、BlueXP  ディザスタリカバリの管理に使用するBlueXP  プロジェクト内の作業環境に追加する必要があります。
+
を参照して https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["オンプレミスのONTAP クラスタを検出"^]





== ワークロードの前提条件

アプリケーション整合性プロセスを確実に成功させるには、次の前提条件を適用します。

* 保護対象のVMでVMwareツール（またはOpen VMツール）が実行されていることを確認します。
* Microsoft SQL Server、Oracle Database、またはその両方を実行しているWindows VMの場合は、データベースのVSS Writerを有効にする必要があります。
* Linuxオペレーティングシステムで実行されているOracleデータベースでは、OracleデータベースSYSDBAロールに対してオペレーティングシステムユーザ認証を有効にする必要があります。

