---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: BlueXPディザスタリカバリを使用するには、いくつかの手順を実行してセットアップします。 
---
= BlueXPディザスタリカバリのためのインフラのセットアップ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
BlueXPディザスタリカバリを使用するには、いくつかの手順を実行してAmazon Web Services（AWS）とBlueXPの両方でセットアップします。


TIP: レビュー link:../get-started/dr-prerequisites.html["前提条件"] 環境の準備が整っていることを確認します。



== BlueXPのディザスタリカバリに備えましょう

* 本番環境を確認します。
+
** 保護するVMがNFSデータストア（ONTAP NFSボリュームを使用）またはVMFSデータストア（NetApp iSCSI LUNを使用）でホストされていることを確認します。
** オンプレミスのONTAPアレイ、vCenter、AWSでホストされるVMwareクラウドインスタンスのクレデンシャルとアクセスキーがあることを確認します。


* ディザスタリカバリサイトを作成または検証します。
+
** Amazon FSxファイルシステムの準備が完了していることを作成または確認します。
** ソースVMとデスティネーションVMがピア関係にあることを確認します。






== VMware Cloud for AWS SDDCのセットアップ

VMware Cloud for AWSのSoftware-Defined Data Center（SDDC）をセットアップ

* Amazon FSx for ONTAPファイルシステムを作成FSx for ONTAPをプロビジョニング、設定Amazon FSX for NetApp ONTAP はフルマネージドサービスで、広く普及しているNetApp ONTAP ファイルシステムを基盤に、信頼性、拡張性、パフォーマンス、機能豊富なファイルストレージを提供します。
* こちらとこちらの手順に従って、 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["リンク"^] https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSx for NetApp ONTAP のクイックスタートガイド"] FSx for NetApp ONTAPのプロビジョニングと設定を行います。
* 作業環境にAmazon FSx for NetApp ONTAPを追加し、FSx for ONTAPのAWSクレデンシャルを追加します。
* AWSでは、次の手順を実行する必要があります。
+
** VMware Cloud on AWSを導入して設定
** VMwareアカウントを使用してSDDCをプロビジョニングします。SDDCがFSx for ONTAPに接続されていることを確認します。






=== VMware Cloudの導入

https://www.vmware.com/products/vmc-on-aws.html["AWS 上の VMware Cloud"^] AWSエコシステム内のVMwareベースのワークロードにクラウドネイティブなエクスペリエンスを提供します。各VMware Software-Defined Data Center（SDDC）はAmazon Virtual Private Cloud（VPC）で実行され、フルVMwareスタック（vCenter Serverを含む）、NSX-Tソフトウェア定義ネットワーク、vSANソフトウェア定義ストレージ、1つ以上のESXiホストを提供し、ワークロードにコンピューティングリソースとストレージリソースを提供します。

AWSでVMC環境を設定するには、次の手順を実行します https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["リンク"^]。パイロットライトクラスタは、ディザスタリカバリにも使用できます。



== ライセンスをセットアップする

BlueXPディザスタリカバリでは、90日間の無償トライアルに登録できます。

次のいずれかを購入できます。

* AWS Marketplaceの従量課金制（PAYGO）サブスクリプション
* お客様所有のライセンスを使用（BYOL）。NetAppライセンスファイル（NLF）です。


を参照してください link:../get-started/dr-licensing.html["BlueXPディザスタリカバリライセンスをセットアップ"]。
