---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: BlueXPディザスタリカバリを使用するには、いくつかの手順を実行してセットアップします。 
---
= BlueXPディザスタリカバリのためのインフラのセットアップ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
BlueXPディザスタリカバリを使用するには、いくつかの手順を実行してAmazon Web Services（AWS）とBlueXPの両方でセットアップします。


TIP: レビュー link:../get-started/dr-prerequisites.html["前提条件"] 環境の準備が整っていることを確認します。



== オンプレミスからオンプレミスへの保護のためのBlueXP  ディザスタリカバリに備えましょう

オンプレミスからオンプレミスへの保護のためにBlueXP  ディザスタリカバリを設定する前に、次の要件を満たしていることを確認してください。

* ONTAPストレージ
+
** ONTAPクレデンシャルがあることを確認します。
** ディザスタリカバリサイトを作成または検証します。
** デスティネーションONTAP SVMを作成または確認します。
** ソースとデスティネーションのONTAP SVMにピア関係が設定されていることを確認します。


* vCenterクラスタ
+
** 保護するVMがNFSデータストア（ONTAP NFSボリュームを使用）またはVMFSデータストア（NetApp iSCSI LUNを使用）でホストされていることを確認します。
** BlueXP  DRの確認link:../reference/vcenter-privileges.html["vCenter Privileges"]が必要です。
** ディザスタリカバリユーザアカウント（デフォルトのvCenter管理者アカウントではない）を作成し、そのアカウントにvCenter Privilegesを割り当てます。






== AWSを使用したオンプレミスからクラウドへの保護のためのBlueXP  ディザスタリカバリに備えましょう

AWSを使用してオンプレミスからクラウドへの保護を実現するBlueXP  ディザスタリカバリを設定するには、以下を設定する必要があります。

* AWS FSx for NetApp ONTAPのセットアップ
* VMware Cloud on AWS SDDCのセットアップ




=== AWS FSx for NetApp ONTAPのセットアップ

* Amazon FSx for NetApp ONTAPファイルシステムを作成
+
** FSx for ONTAPをプロビジョニング、設定Amazon FSx for NetApp ONTAPは、NetApp ONTAPファイルシステム上に構築された、信頼性、拡張性、パフォーマンス、機能豊富なファイルストレージを提供するフルマネージドサービスです。
** との https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Amazon FSx for NetApp ONTAP のクイックスタートガイド"]手順に従って、 https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["テクニカルレポート4938：『Mount Amazon FSx ONTAP as an NFS datastore with VMware Cloud on AWS』"^]FSx for ONTAPのプロビジョニングと設定を行います。


* 作業環境にAmazon FSx for ONTAPを追加し、FSx for ONTAPのAWSクレデンシャルを追加します。
* AWS FSx for ONTAPインスタンスでデスティネーションONTAP SVMを作成または確認します。
* ソースのオンプレミスONTAPクラスタとBlueXP  のFSx for ONTAPインスタンスの間でレプリケーションを設定


詳細な手順については、を参照してください https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["FSx for ONTAP作業環境の設定方法"^]。



=== VMware Cloud on AWS SDDCのセットアップ

https://www.vmware.com/products/vmc-on-aws.html["AWS 上の VMware Cloud"^] AWSエコシステム内のVMwareベースのワークロードにクラウドネイティブなエクスペリエンスを提供します。各VMware Software-Defined Data Center（SDDC）はAmazon Virtual Private Cloud（VPC）で実行され、フルVMwareスタック（vCenter Serverを含む）、NSX-Tソフトウェア定義ネットワーク、vSANソフトウェア定義ストレージ、1つ以上のESXiホストを提供し、ワークロードにコンピューティングリソースとストレージリソースを提供します。

AWSでVMware Cloud環境を構成するには、の手順に従い https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["AWS に仮想化環境を導入して設定"^]ます。パイロットライトクラスタはディザスタリカバリにも使用できます。
