---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: BlueXPのディザスタリカバリは、ディザスタリカバリのワークフローを自動化する、クラウドベースのディザスタリカバリサービスです。VMware向けBlueXPディザスタリカバリでは、ONTAPストレージを実行するオンプレミスのVMwareワークロードを、NetAppクラウドストレージを使用してディザスタリカバリサイトとして、パブリッククラウドにあるVMwareのSoftware-Defined Data Centerにレプリケートできます。 
---
= BlueXP  ディザスタリカバリの新機能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXPディザスタリカバリの新機能をご紹介します。



== 2025年6月30日

バージョン4.2.4P2



=== 発見の改善

このアップデートにより検出プロセスが改善され、検出に必要な時間が短縮されます。



== 2025年6月23日

バージョン4.2.4P1



=== サブネットマッピングの改善

このアップデートでは、「サブネットマッピングの追加と編集」ダイアログに新しい検索機能が追加されました。検索語を入力するだけで特定のサブネットを素早く見つけられるため、サブネットマッピングの管理が容易になります。



== 2025年6月9日

バージョン4.2.4



=== Windows ローカル管理者パスワードソリューション (LAPS) のサポート

Windows ローカル管理者パスワード ソリューション (Windows LAPS) は、Active Directory 上のローカル管理者アカウントのパスワードを自動的に管理およびバックアップする Windows 機能です。

ドメインコントローラーの詳細を入力することで、サブネットマッピングオプションを選択し、LAPSオプションをチェックできるようになりました。このオプションを使用すると、仮想マシンごとにパスワードを入力する必要がなくなります。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



== 2025年5月13日

バージョン4.2.3



=== サブネットマッピング

このリリースでは、サブネットマッピングを使用してフェイルオーバー時のIPアドレスを新しい方法で管理できます。これにより、各vCenterにサブネットを追加できます。その場合は、IPv4 CIDR、デフォルトゲートウェイ、および各仮想ネットワークのDNSを定義します。

フェイルオーバー時に、BlueXP  ディザスタリカバリは、マッピングされた仮想ネットワーク用に提供されたCIDRを参照して、各vNICの適切なIPアドレスを決定し、それを使用して新しいIPアドレスを取得します。

例：

* networkA = 10.1.1.0/24
* ネットワークB = 192.168.1.0/24


VM1には、NetworkAに接続されたvNIC（10.1.1.50）があります。NetworkAは、レプリケーションプラン設定でNetworkBにマッピングされます。

フェイルオーバー時、BlueXP  ディザスタリカバリは元のIPアドレス（10.1.1）のネットワーク部分を置き換え、元のIPアドレス（10.1.1.50）のホストアドレス（.50）を維持します。VM1の場合、BlueXP  ディザスタリカバリは、NetworkBのCIDR設定を確認し、ホスト部分（.50）を維持しながら、NetworkBネットワーク部分192.168.1を使用してVM1の新しいIPアドレスを作成します。新しいIPは192.168.1.50になります。

つまり、ホストアドレスは同じままですが、ネットワークアドレスはサイトサブネットマッピングで設定されているものに置き換えられます。これにより、フェイルオーバー時のIPアドレスの再割り当てをより簡単に管理できます。特に、数百のネットワークと数千のVMを管理する必要がある場合に便利です。

サイトにサブネットマッピングを含める方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenterサーバサイトを追加"]。



=== 保護をスキップ

レプリケーションプランのフェイルオーバー後にサービスが逆保護関係を自動的に作成しないように、保護をスキップできるようになりました。これは、BlueXP  ディザスタリカバリでリストアしたサイトをオンラインに戻す前に、そのサイトで追加の処理を実行する場合に便利です。

フェイルオーバーを開始すると、デフォルトでは、元のソースサイトがオンラインの場合、レプリケーションプランの各ボリュームに対して逆保護関係が自動的に作成されます。これは、サービスがターゲットサイトからソースサイトへのSnapMirror関係を作成することを意味します。フェイルバックを開始すると、SnapMirror関係も自動的に反転されます。

フェイルオーバーを開始するときに、*[Skip protection]*オプションを選択できるようになりました。これにより、サービスはSnapMirror関係を自動的に反転しません。代わりに、書き込み可能なボリュームはレプリケーション計画の両側に残ります。

元のソースサイトがオンラインに戻ったら、レプリケーションプランの[アクション]メニューから*[リソースの保護]*を選択して、逆保護を設定できます。これにより、プラン内の各ボリュームに対して逆レプリケーション関係の作成が試行されます。保護が回復するまで、このジョブを繰り返し実行できます。保護が復元されたら、通常の方法でフェイルバックを開始できます。

保護のスキップの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



=== SnapMirrorスケジュールによるレプリケーション計画の更新

BlueXP  ディザスタリカバリでは、標準のONTAP SnapMirrorポリシースケジューラやONTAPとのサードパーティ統合など、外部のSnapshot管理ソリューションの使用がサポートされるようになりました。レプリケーションプラン内のすべてのデータストア（ボリューム）にすでに別の場所で管理されているSnapMirror関係がある場合は、それらのSnapshotをBlueXP  ディザスタリカバリのリカバリポイントとして使用できます。

設定するには、[Replication plan]>[Resource mapping]セクションで、データストアマッピングの設定時に*[Use platform managed backups and retention schedules]*チェックボックスをオンにします。

このオプションを選択した場合、BlueXP  ディザスタリカバリではバックアップスケジュールが設定されません。ただし、テスト、フェイルオーバー、フェイルバック操作のためにスナップショットが作成される可能性があるため、保持スケジュールを設定する必要があります。

この設定後、サービスは定期的にスケジュールされたスナップショットを作成せず、代わりに外部エンティティに依存してこれらのスナップショットを作成および更新します。

レプリケーションプランでの外部スナップショットソリューションの使用の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



== 2025年4月16日

バージョン4.2.2



=== VMのスケジュールされた検出

BlueXP  ディザスタリカバリでは、24時間に1回検出が実行されます。このリリースでは、ニーズに合わせて調査スケジュールをカスタマイズし、必要なときにパフォーマンスへの影響を軽減できるようになりました。たとえば、VMの数が多い場合は、検出スケジュールを48時間ごとに実行するように設定できます。VMの数が少ない場合は、検出スケジュールを12時間ごとに実行するように設定できます。

検出をスケジュールしない場合は、スケジュールされた検出オプションを無効にして、いつでも手動で検出を更新できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["vCenterサーバサイトを追加"]。



=== リソースグループデータストアのサポート

これまでは、VMごとにのみリソースグループを作成できました。このリリースでは、データストア別にリソースグループを作成できます。レプリケーション計画を作成し、その計画のリソースグループを作成すると、データストア内のすべてのVMが一覧表示されます。これは、多数のVMがあり、それらをデータストアでグループ化する場合に便利です。

データストアを含むリソースグループは、次の方法で作成できます。

* データストアを使用してリソースグループを追加する場合は、データストアのリストが表示されます。1つ以上のデータストアを選択してリソースグループを作成できます。
* レプリケーション計画を作成し、その計画内にリソースグループを作成すると、データストア内のVMが表示されます。


詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 無償トライアルまたはライセンスの有効期限に関する通知

このリリースでは、ライセンスを取得する時間を確保するために、無料トライアルが60日後に期限切れになることを通知します。また、このリリースでは、ライセンスの有効期限が切れる日に通知が送信されます。



=== サービス更新の通知

このリリースでは、サービスがアップグレードされ、サービスがメンテナンスモードになったことを示すバナーが上部に表示されます。バナーはサービスのアップグレード中に表示され、アップグレードが完了すると消えます。アップグレードの進行中もUIで作業を続行できますが、新しいジョブを送信することはできません。スケジュールされたジョブは、更新が完了してサービスが本番モードに戻ると実行されます。



== 2025年3月10日

バージョン4.2.1



=== インテリジェントなプロキシサポート

BlueXP  Connectorはインテリジェントプロキシをサポートしています。インテリジェントプロキシは、オンプレミス環境をBlueXP  サービスに接続するための、軽量で安全で効率的な方法です。VPNや直接インターネットアクセスを必要とせずに、環境とBlueXP  サービスの間に安全な接続を提供します。この最適化されたプロキシ実装により、ローカルネットワーク内のAPIトラフィックがオフロードされます。

プロキシが設定されている場合、BlueXP  ディザスタリカバリはVMwareまたはONTAPとの直接通信を試み、直接通信に失敗した場合は設定されたプロキシを使用します。

BlueXP  ディザスタリカバリプロキシを実装するには、HTTPSプロトコルを使用してコネクタとvCenter ServerおよびONTAPアレイをポート443で通信する必要があります。コネクタ内のBlueXP  ディザスタリカバリエージェントは、アクションの実行時にVMware vSphere、VC、またはONTAPと直接通信します。

BlueXP  ディザスタリカバリ用のインテリジェントプロキシの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["BlueXPディザスタリカバリのためのインフラのセットアップ"]。

BlueXP  で設定される一般的なプロキシの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["プロキシサーバを使用するようにコネクタを設定します"^]。



=== 無償トライアルをいつでも終了

無料トライアルはいつでも停止することも、期限が切れるまで待つこともできます。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["無償トライアルを終了する"]



== 2025年2月19日

バージョン4.2



=== VMFSストレージ上のVMとデータストアに対するASA R2のサポート

このリリースのBlueXP  ディザスタリカバリでは、VMFSストレージ上のVMとデータストアでASA R2がサポートされます。ASA R2システムでは、ONTAPソフトウェアは重要なSAN機能をサポートし、SAN環境でサポートされていない機能を削除します。

このリリースでは、ASA R2で次の機能がサポートされます。

* プライマリストレージのコンシステンシグループプロビジョニング（フラットコンシステンシグループのみ、階層構造を持たない1レベルのみ）
* バックアップ（整合グループ）処理（SnapMirrorの自動化など）


BlueXP  ディザスタリカバリでのASA R2のサポートには、ONTAP 9.16.1が使用されます。

データストアはONTAPボリュームまたはASA R2ストレージユニットにマウントできますが、BlueXP  ディザスタリカバリのリソースグループにONTAPのデータストアとASA R2のデータストアの両方を含めることはできません。リソースグループには、ONTAPのデータストアまたはASA R2のデータストアを選択できます。



== 2024年10月30日



=== レポート作成

環境の分析に役立つレポートを生成してダウンロードできるようになりました。事前設計されたレポートには、フェイルオーバーとフェイルバックの概要、すべてのサイトのレプリケーションの詳細、過去7日間のジョブの詳細が表示されます。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["ディザスタリカバリレポートの作成"]。



=== 30日間の無償トライアル

BlueXP  ディザスタリカバリの30日間無償トライアルに申し込むことができます。以前は、無料トライアルは90日間でした。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスをセットアップする"]。



=== レプリケーション計画の無効化と有効化

以前のリリースでは、日次スケジュールと週次スケジュールをサポートするために必要なフェイルオーバーテストスケジュールの構造が更新されていました。この更新では、新しい日次および週次フェイルオーバーテストスケジュールを使用できるように、既存のレプリケーションプランをすべて無効にして再度有効にする必要がありました。これは1回限りの要件です。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. 計画を選択し、[Actions]アイコンを選択してドロップダウンメニューを表示します。
. [*Disable*] を選択します。
. 数分後、*[有効化]*を選択します。




=== フォルダマッピング

レプリケーション計画を作成してコンピューティングリソースをマッピングするときに、フォルダをマッピングして、データセンター、クラスタ、およびホスト用に指定したフォルダにVMをリカバリできるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== フェイルオーバー、フェイルバック、テストフェイルオーバーに使用できるVMの詳細

障害が発生し、フェイルオーバーの開始、フェイルバックの実行、またはフェイルオーバーのテストを行うときに、VMの詳細を確認し、再起動しなかったVMを特定できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



=== 順序付けされた起動順序でのVM起動遅延

レプリケーションプランを作成するときに、プラン内の各VMにブート遅延を設定できるようになりました。これにより、優先順位の高いすべてのVMが実行されてから、以降の優先順位の高いVMが起動されるように、VMの起動順序を設定できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== VMオペレーティングシステム情報

レプリケーションプランを作成すると、プラン内の各VMのオペレーティングシステムが表示されるようになります。これは、VMを1つのリソースグループにグループ化する方法を決定する際に役立ちます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== VM名のエイリアス設定

レプリケーション計画を作成するときに、ディザスタリカバリSITでVM名にプレフィックスとサフィックスを追加できるようになりました。これにより、プラン内のVMにわかりやすい名前を付けることができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 古いSnapshotをクリーンアップ

指定した保持数を超えて不要になったSnapshotは削除できます。Snapshotの保持数を減らすと、時間の経過とともにSnapshotが蓄積される可能性があります。削除してスペースを解放できるようになりました。これは、オンデマンドで、またはレプリケーションプランを削除するときにいつでも実行できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["サイト、リソースグループ、レプリケーションプラン、データストア、仮想マシンの情報を管理します。"]。



=== スナップショットの調整

ソースとターゲットの間で同期されていないスナップショットを調整できるようになりました。これは、BlueXP  ディザスタリカバリ以外のターゲットでSnapshotが削除された場合に発生することがあります。サービスは、ソース上のスナップショットを24時間ごとに自動的に削除します。ただし、これはオンデマンドで実行できます。この機能を使用すると、すべてのサイトでSnapshotの整合性を確保できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["レプリケーション計画の管理"]。



== 2024年9月20日



=== オンプレミスからオンプレミスへのVMware VMFSデータストアのサポート

このリリースでは、オンプレミスストレージに保護されたiSCSIおよびFC用に、VMware vSphere Virtual Machine File System（VMFS）データストアにマウントされたVMがサポートされます。以前は、iSCSIおよびFC用にVMFSデータストアをサポートするテクノロジpreview_supportingを提供していました。

iSCSIプロトコルとFCプロトコルの両方に関するその他の考慮事項を次に示します。

* FCは、レプリケーションではなく、クライアントフロントエンドプロトコルをサポートします。
* BlueXP  ディザスタリカバリでは、各ONTAPでサポートされるLUNは1つだけです。ボリュームに複数のLUNを含めることはできません。
* レプリケーション計画については、デスティネーションONTAPボリュームで、保護対象VMをホストしているソースONTAPボリュームと同じプロトコルを使用する必要があります。たとえば、ソースでFCプロトコルを使用している場合は、デスティネーションでもFCを使用する必要があります。




== 2024 年 8 月 2 日



=== FCに対応したオンプレミスからオンプレミスのVMware VMFSデータストアのサポート

このリリースには、FCをオンプレミスストレージに保護するために、VMware vSphere Virtual Machine File System（VMFS）データストアにマウントされたVMの_ technology preview_ofのサポートが含まれています。以前は、iSCSI用のVMFSデータストアをサポートするテクノロジプレビューを提供していました。


NOTE: NetAppでは、プレビューしたワークロード容量に対して課金されることはありません。



=== ジョブのキャンセル

このリリースでは、Job Monitor UIでジョブをキャンセルできるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["ジョブの監視"]。



== 2024年7月17日



=== フェイルオーバーテストスケジュール

このリリースでは、日次スケジュールと週次スケジュールをサポートするために必要なフェイルオーバーテストスケジュールの構造が更新されています。この更新では、新しい毎日および毎週のフェイルオーバーテストスケジュールを使用できるように、既存のレプリケーションプランをすべて無効にして再度有効にする必要があります。これは1回限りの要件です。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. 計画を選択し、[Actions]アイコンを選択してドロップダウンメニューを表示します。
. [*Disable*] を選択します。
. 数分後、*[有効化]*を選択します。




=== レプリケーション計画の更新

このリリースには、レプリケーション計画データの更新が含まれています。これにより、「スナップショットが見つかりません」の問題が解決されます。そのためには、すべてのレプリケーション計画の保持数を1に変更し、オンデマンドのSnapshotを開始する必要があります。このプロセスでは、新しいバックアップが作成され、古いバックアップがすべて削除されます。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. レプリケーション計画を選択し、*[フェイルオーバーマッピング]*タブをクリックし、*[編集]*鉛筆アイコンをクリックします。
. [Datastores]*の矢印をクリックして展開します。
. レプリケーション計画の保持数の値をメモします。これらの手順が完了したら、この元の値を元に戻す必要があります。
. カウントを1に減らします。
. オンデマンドのスナップショットを開始します。これを行うには、[Replication plan]ページでプランを選択し、[Actions]アイコンをクリックして*[Take snapshot now]*を選択します。
. Snapshotジョブが正常に完了したら、レプリケーションプランの数を、最初の手順でメモした元の値に戻します。
. 既存のすべてのレプリケーションプランについて、上記の手順を繰り返します。




== 2024年7月5日

このBlueXPディザスタリカバリリリースには、次の更新が含まれています。



=== AFF Aシリーズノサポート

このリリースでは、NetApp AFF Aシリーズハードウェアプラットフォームがサポートされます。



=== オンプレミスからオンプレミスへのVMware VMFSデータストアのサポート

このリリースには、オンプレミスストレージで保護されたVMware vSphere Virtual Machine File System（VMFS）データストアにマウントされたVMに対する_ technology preview_ofのサポートが含まれています。このリリースでは、オンプレミスのVMwareワークロードからVMFSデータストアを使用するオンプレミスのVMware環境へのディザスタリカバリがテクノロジプレビューでサポートされます。


NOTE: NetAppでは、プレビューしたワークロード容量に対して課金されることはありません。



=== レプリケーション計画の更新

[Applications]ページでデータストアでVMをフィルタリングし、[Resource mapping]ページでターゲットの詳細を選択すると、レプリケーションプランを簡単に追加できます。を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== レプリケーション計画の編集

このリリースでは、わかりやすくするために[Failover mappings]ページが拡張されました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["計画の管理"]。



=== VMの編集

このリリースでは、計画内のVMの編集プロセスにUIが若干改善されました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["VMの管理"]。



=== アップデートのフェイルオーバー

フェイルオーバーを開始する前に、VMのステータスと電源がオンになっているかオフになっているかを確認できるようになりました。フェイルオーバープロセスでは、今すぐSnapshotを作成するか、またはSnapshotを選択できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



=== フェイルオーバーテストスケジュール

フェイルオーバーテストを編集し、フェイルオーバーテストのスケジュールを毎日、毎週、毎月設定できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["計画の管理"]。



=== 前提条件に関する情報の更新

BlueXP  ディザスタリカバリの前提条件に関する情報が更新されました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["BlueXPディザスタリカバリの前提条件"]。



== 2024年5月15日

このBlueXPディザスタリカバリリリースには、次の更新が含まれています。



=== オンプレミスからオンプレミスへのVMwareワークロードのレプリケーション

これは現在、一般提供機能としてリリースされています。以前は、機能が制限されたテクノロジプレビューでした。



=== ライセンスの更新

BlueXP  ディザスタリカバリでは、90日間の無償トライアルにサインアップするか、Amazon Marketplaceで従量課金制（PAYGO）サブスクリプションを購入するか、NetApp営業担当またはNetAppサポートサイト（NSS）から取得したNetAppライセンスファイル（NLF）であるお客様所有のライセンスを使用（BYOL）できます。

BlueXPディザスタリカバリ用のライセンスのセットアップの詳細については、を参照してください。 link:../get-started/dr-licensing.html["ライセンスをセットアップする"]。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。



== 2024年3月5日

これはBlueXPディザスタリカバリのGeneral Availabilityリリースであり、次の更新が含まれています。



=== ライセンスの更新

BlueXP  ディザスタリカバリでは、90日間の無償トライアルにサインアップするか、NetApp営業担当から入手したNetAppライセンスファイル（NLF）であるお客様所有のライセンスを使用（BYOL）できます。ライセンスのシリアル番号を使用して、BlueXPデジタルウォレットでBYOLをアクティブ化できます。BlueXPディザスタリカバリの料金は、データストアのプロビジョニング済み容量に基づいて計算されます。

BlueXPディザスタリカバリ用のライセンスのセットアップの詳細については、を参照してください。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスをセットアップする"]。

すべての* BlueXPサービスのライセンス管理の詳細については、 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["すべてのBlueXPサービスのライセンスを管理します。"^]。



=== スケジュールを編集します

このリリースでは、コンプライアンステストとフェイルオーバーテストをテストするスケジュールを設定して、必要に応じて正しく動作することを確認できるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



== 2024年2月1日

このBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== ネットワークの機能拡張

このリリースでは、VMのCPU値とRAM値のサイズを変更できるようになりました。VMのネットワークDHCPまたは静的IPアドレスを選択することもできます。

* DHCP：このオプションを選択した場合は、VMのクレデンシャルを指定します。
* 静的IP：ソースVMと同じ情報または異なる情報を選択できます。ソースと同じを選択した場合は、クレデンシャルを入力する必要はありません。一方、ソースと異なる情報を使用する場合は、クレデンシャル、IPアドレス、サブネットマスク、DNS、およびゲートウェイの情報を指定できます。


詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== カスタムスクリプト

フェイルオーバー後のプロセスとして含めることができるようになりました。カスタムスクリプトを使用すると、フェイルオーバープロセスのあとにBlueXPディザスタリカバリでスクリプトを実行できます。たとえば、フェイルオーバーの完了後にすべてのデータベーストランザクションを再開するカスタムスクリプトを使用できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのフェイルオーバー"]。



=== SnapMirror関係

レプリケーション計画の作成時にSnapMirror関係を作成できるようになりました。以前は、BlueXPのディザスタリカバリ以外で関係を作成する必要がありました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 整合グループ

レプリケーション計画を作成する際に、異なるボリュームや異なるSVMのVMを含めることができます。BlueXPディザスタリカバリでは、すべてのボリュームを含めて整合グループSnapshotを作成し、すべてのセカンダリサイトを更新します。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== VM電源投入遅延オプション

レプリケーション計画を作成するときに、リソースグループにVMを追加できます。リソースグループを使用すると、各VMに遅延を設定して、遅延シーケンスで電源を投入することができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== アプリケーションと整合性のある Snapshot コピー

アプリケーションと整合性のあるSnapshotコピーを作成するように指定できます。サービスはアプリケーションを休止し、Snapshotを作成してアプリケーションの整合性のある状態を取得します。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



== 2024年1月11日

今回のBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== ダッシュボードの高速化

このリリースでは、ダッシュボードから他のページの情報にすばやくアクセスできます。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。



== 2023年10月20日

今回のBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== オンプレミスのNFSベースのVMwareワークロードを保護

BlueXPディザスタリカバリを使用すると、オンプレミスのNFSベースのVMwareワークロードを、パブリッククラウドに加えてオンプレミスのNFSベースのVMware環境への災害から保護できます。BlueXPディザスタリカバリは、ディザスタリカバリ計画の完成をオーケストレーションします。


NOTE: このプレビューサービスでは、NetAppは、一般提供前にサービスの詳細、内容、スケジュールを変更する権利を留保します。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。



== 2023年9月27日

今回のBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== ダッシュボードの更新

ダッシュボードのオプションをクリックすると、情報をすばやく確認しやすくなります。また、ダッシュボードにフェイルオーバーと移行のステータスが表示されるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["ダッシュボードでディザスタリカバリプランの健全性を表示する"]。



=== レプリケーション計画の更新

* * RPO *：レプリケーションプランの[データストア]セクションに、目標復旧時点（RPO）と保持数を入力できるようになりました。これは、設定された時間より前に存在する必要があるデータの量を示します。たとえば、5分に設定した場合、災害が発生してもビジネスクリティカルなニーズに影響を与えることなく、システムのデータが最大5分失われる可能性があります。
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。

* *ネットワークの機能拡張*：レプリケーション計画の仮想マシンセクションでソースとターゲットの場所間のネットワークをマッピングする際に、BlueXPディザスタリカバリでDHCPと静的IPの2つのオプションが提供されるようになりました。以前は、DHCPのみがサポートされていました。静的IPの場合は、サブネット、ゲートウェイ、およびDNSサーバを設定します。また、仮想マシンのクレデンシャルを入力できるようになりました。
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。

* *スケジュールの編集*：レプリケーションプランのスケジュールを更新できるようになりました。
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["リソースの管理"]。

* * SnapMirrorの自動化*：このリリースでレプリケーション計画を作成する際に、ソースボリュームとターゲットボリューム間のSnapMirror関係を次のいずれかの構成で定義できます。
+
** 1対1
** ファンアウトアーキテクチャで1対多
** コンシステンシグループとして多対1
** 多対多
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。







== 2023年8月1日



=== BlueXP  ディザスタリカバリのプレビュー

BlueXPディザスタリカバリプレビューは、ディザスタリカバリのワークフローを自動化する、クラウドベースのディザスタリカバリサービスです。当初は、BlueXPのディザスタリカバリプレビューで、NetAppストレージを実行するオンプレミスのNFSベースのVMwareワークロードを、Amazon FSx for ONTAPを使用してAWS上のVMware Cloud（VMC）に保護できます。


NOTE: このプレビューサービスでは、NetAppは、一般提供前にサービスの詳細、内容、スケジュールを変更する権利を留保します。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。

このリリースでは、次の更新が行われています。



=== リソースグループのブート順序の更新

ディザスタリカバリ計画またはレプリケーション計画を作成するときに、仮想マシンを機能リソースグループに追加できます。リソースグループを使用すると、依存する一連の仮想マシンを、要件を満たす論理グループにまとめることができます。たとえば、リカバリ時に実行できるブート順序をグループに含めることができます。このリリースでは、各リソースグループに1つ以上の仮想マシンを含めることができます。仮想マシンは、計画に含める順序に基づいてパワーオンされます。を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["レプリケートするアプリケーションの選択とリソースグループの割り当て"]。



=== レプリケーションの検証

ディザスタリカバリまたはレプリケーションの計画を作成し、ウィザードで繰り返しを特定し、ディザスタリカバリサイトへのレプリケーションを開始したら、30分ごとにBlueXP  ディザスタリカバリによって、計画に従ってレプリケーションが実際に実行されているかどうかが検証されます。進捗状況は[Job Monitor]ページで監視できます。を参照してください  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["アプリケーションを別のサイトにレプリケート"]。



=== レプリケーションプランで目標復旧時点（RPO）の転送スケジュールを表示

ディザスタリカバリ計画またはレプリケーション計画を作成するときは、VMを選択します。このリリースでは、データストアまたはVMに関連付けられている各ボリュームに関連付けられているSnapMirrorを確認できるようになりました。SnapMirrorスケジュールに関連付けられているRPO転送スケジュールも確認できます。RPOは、災害発生後にリカバリするのに十分なバックアップスケジュールであるかどうかを判断するのに役立ちます。を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== ジョブモニタの更新

[Job Monitor]ページに[Refresh]オプションが追加され、処理の最新ステータスを確認できるようになりました。を参照してください  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["ディザスタリカバリジョブを監視する"]。



== 2023年5月18日

これは、BlueXPディザスタリカバリの初版リリースです。



=== クラウドベースのディザスタリカバリサービス

BlueXPのディザスタリカバリは、ディザスタリカバリのワークフローを自動化する、クラウドベースのディザスタリカバリサービスです。当初は、BlueXPのディザスタリカバリプレビューで、NetAppストレージを実行するオンプレミスのNFSベースのVMwareワークロードを、Amazon FSx for ONTAPを使用してAWS上のVMware Cloud（VMC）に保護できます。

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。
