---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas 
summary: BlueXPのディザスタリカバリは、ディザスタリカバリのワークフローを自動化する、クラウドベースのディザスタリカバリサービスです。VMware向けBlueXPディザスタリカバリでは、ONTAPストレージを実行するオンプレミスのVMwareワークロードを、NetAppクラウドストレージを使用してディザスタリカバリサイトとして、パブリッククラウドにあるVMwareのSoftware-Defined Data Centerにレプリケートできます。 
---
= BlueXP  ディザスタリカバリの新機能
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BlueXPディザスタリカバリの新機能をご紹介します。



== 2025年2月19日

バージョン4.2



=== VMFSストレージ上のVMとデータストアに対するASA R2のサポート

このリリースのBlueXP  ディザスタリカバリでは、VMFSストレージ上のVMとデータストアでASA R2がサポートされます。ASA R2システムでは、ONTAPソフトウェアは重要なSAN機能をサポートし、SAN環境でサポートされていない機能を削除します。

このリリースでは、ASA R2で次の機能がサポートされます。

* プライマリストレージのコンシステンシグループプロビジョニング（フラットコンシステンシグループのみ、階層構造を持たない1レベルのみ）
* バックアップ（整合グループ）処理（SnapMirrorの自動化など）


BlueXP  ディザスタリカバリでのASA R2のサポートには、ONTAP 9.16.1が使用されます。

データストアはONTAPボリュームまたはASA R2ストレージユニットにマウントできますが、BlueXP  ディザスタリカバリのリソースグループにONTAPのデータストアとASA R2のデータストアの両方を含めることはできません。リソースグループには、ONTAPのデータストアまたはASA R2のデータストアを選択できます。



== 2024年10月30日



=== レポート作成

環境の分析に役立つレポートを生成してダウンロードできるようになりました。事前設計されたレポートには、フェイルオーバーとフェイルバックの概要、すべてのサイトのレプリケーションの詳細、過去7日間のジョブの詳細が表示されます。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["ディザスタリカバリレポートの作成"]。



=== 30日間の無償トライアル

BlueXP  ディザスタリカバリの30日間無償トライアルに申し込むことができます。以前は、無料トライアルは90日間でした。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスをセットアップする"]。



=== レプリケーション計画の無効化と有効化

以前のリリースでは、日次スケジュールと週次スケジュールをサポートするために必要なフェイルオーバーテストスケジュールの構造が更新されていました。この更新では、新しい日次および週次フェイルオーバーテストスケジュールを使用できるように、既存のレプリケーションプランをすべて無効にして再度有効にする必要がありました。これは1回限りの要件です。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. 計画を選択し、[Actions]アイコンを選択してドロップダウンメニューを表示します。
. [*Disable*] を選択します。
. 数分後、*[有効化]*を選択します。




=== フォルダマッピング

レプリケーション計画を作成してコンピューティングリソースをマッピングするときに、フォルダをマッピングして、データセンター、クラスタ、およびホスト用に指定したフォルダにVMをリカバリできるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== フェイルオーバー、フェイルバック、テストフェイルオーバーに使用できるVMの詳細

障害が発生し、フェイルオーバーの開始、フェイルバックの実行、またはフェイルオーバーのテストを行うときに、VMの詳細を確認し、再起動しなかったVMを特定できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



=== 順序付けされた起動順序でのVM起動遅延

レプリケーションプランを作成するときに、プラン内の各VMにブート遅延を設定できるようになりました。これにより、優先順位の高いすべてのVMが実行されてから、以降の優先順位の高いVMが起動されるように、VMの起動順序を設定できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== VMオペレーティングシステム情報

レプリケーションプランを作成すると、プラン内の各VMのオペレーティングシステムが表示されるようになります。これは、VMを1つのリソースグループにグループ化する方法を決定する際に役立ちます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== VM名のエイリアス設定

レプリケーション計画を作成するときに、ディザスタリカバリSITでVM名にプレフィックスとサフィックスを追加できるようになりました。これにより、プラン内のVMにわかりやすい名前を付けることができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 古いSnapshotをクリーンアップ

指定した保持数を超えて不要になったSnapshotは削除できます。Snapshotの保持数を減らすと、時間の経過とともにSnapshotが蓄積される可能性があります。削除してスペースを解放できるようになりました。これは、オンデマンドで、またはレプリケーションプランを削除するときにいつでも実行できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["サイト、リソースグループ、レプリケーションプラン、データストア、仮想マシンの情報を管理します。"]。



=== スナップショットの調整

ソースとターゲットの間で同期されていないスナップショットを調整できるようになりました。これは、BlueXP  ディザスタリカバリ以外のターゲットでSnapshotが削除された場合に発生することがあります。サービスは、ソース上のスナップショットを24時間ごとに自動的に削除します。ただし、これはオンデマンドで実行できます。この機能を使用すると、すべてのサイトでSnapshotの整合性を確保できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["レプリケーション計画の管理"]。



== 2024年9月20日



=== オンプレミスからオンプレミスへのVMware VMFSデータストアのサポート

このリリースでは、オンプレミスストレージに保護されたiSCSIおよびFC用に、VMware vSphere Virtual Machine File System（VMFS）データストアにマウントされたVMがサポートされます。以前は、iSCSIおよびFC用にVMFSデータストアをサポートするテクノロジpreview_supportingを提供していました。

iSCSIプロトコルとFCプロトコルの両方に関するその他の考慮事項を次に示します。

* FCは、レプリケーションではなく、クライアントフロントエンドプロトコルをサポートします。
* BlueXP  ディザスタリカバリでは、各ONTAPでサポートされるLUNは1つだけです。ボリュームに複数のLUNを含めることはできません。
* レプリケーション計画については、デスティネーションONTAPボリュームで、保護対象VMをホストしているソースONTAPボリュームと同じプロトコルを使用する必要があります。たとえば、ソースでFCプロトコルを使用している場合は、デスティネーションでもFCを使用する必要があります。




== 2024 年 8 月 2 日



=== FCに対応したオンプレミスからオンプレミスのVMware VMFSデータストアのサポート

このリリースには、FCをオンプレミスストレージに保護するために、VMware vSphere Virtual Machine File System（VMFS）データストアにマウントされたVMの_ technology preview_ofのサポートが含まれています。以前は、iSCSI用のVMFSデータストアをサポートするテクノロジプレビューを提供していました。


NOTE: NetAppでは、プレビューしたワークロード容量に対して課金されることはありません。



=== ジョブのキャンセル

このリリースでは、Job Monitor UIでジョブをキャンセルできるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["ジョブの監視"]。



== 2024年7月17日



=== フェイルオーバーテストスケジュール

このリリースでは、日次スケジュールと週次スケジュールをサポートするために必要なフェイルオーバーテストスケジュールの構造が更新されています。この更新では、新しい毎日および毎週のフェイルオーバーテストスケジュールを使用できるように、既存のレプリケーションプランをすべて無効にして再度有効にする必要があります。これは1回限りの要件です。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. 計画を選択し、[Actions]アイコンを選択してドロップダウンメニューを表示します。
. [*Disable*] を選択します。
. 数分後、*[有効化]*を選択します。




=== レプリケーション計画の更新

このリリースには、レプリケーション計画データの更新が含まれています。これにより、「スナップショットが見つかりません」の問題が解決されます。そのためには、すべてのレプリケーション計画の保持数を1に変更し、オンデマンドのSnapshotを開始する必要があります。このプロセスでは、新しいバックアップが作成され、古いバックアップがすべて削除されます。

その方法は次のとおりです。

. トップメニューから*レプリケーションプラン*を選択します。
. レプリケーション計画を選択し、*[フェイルオーバーマッピング]*タブをクリックし、*[編集]*鉛筆アイコンをクリックします。
. [Datastores]*の矢印をクリックして展開します。
. レプリケーション計画の保持数の値をメモします。これらの手順が完了したら、この元の値を元に戻す必要があります。
. カウントを1に減らします。
. オンデマンドのスナップショットを開始します。これを行うには、[Replication plan]ページでプランを選択し、[Actions]アイコンをクリックして*[Take snapshot now]*を選択します。
. Snapshotジョブが正常に完了したら、レプリケーションプランの数を、最初の手順でメモした元の値に戻します。
. 既存のすべてのレプリケーションプランについて、上記の手順を繰り返します。




== 2024年7月5日

このBlueXPディザスタリカバリリリースには、次の更新が含まれています。



=== AFF Aシリーズノサポート

このリリースでは、NetApp AFF Aシリーズハードウェアプラットフォームがサポートされます。



=== オンプレミスからオンプレミスへのVMware VMFSデータストアのサポート

このリリースには、オンプレミスストレージで保護されたVMware vSphere Virtual Machine File System（VMFS）データストアにマウントされたVMに対する_ technology preview_ofのサポートが含まれています。このリリースでは、オンプレミスのVMwareワークロードからVMFSデータストアを使用するオンプレミスのVMware環境へのディザスタリカバリがテクノロジプレビューでサポートされます。


NOTE: NetAppでは、プレビューしたワークロード容量に対して課金されることはありません。



=== レプリケーション計画の更新

[Applications]ページでデータストアでVMをフィルタリングし、[Resource mapping]ページでターゲットの詳細を選択すると、レプリケーションプランを簡単に追加できます。を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== レプリケーション計画の編集

このリリースでは、わかりやすくするために[Failover mappings]ページが拡張されました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["計画の管理"]。



=== VMの編集

このリリースでは、計画内のVMの編集プロセスにUIが若干改善されました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["VMの管理"]。



=== アップデートのフェイルオーバー

フェイルオーバーを開始する前に、VMのステータスと電源がオンになっているかオフになっているかを確認できるようになりました。フェイルオーバープロセスでは、今すぐSnapshotを作成するか、またはSnapshotを選択できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのアプリケーションのフェイルオーバー"]。



=== フェイルオーバーテストスケジュール

フェイルオーバーテストを編集し、フェイルオーバーテストのスケジュールを毎日、毎週、毎月設定できるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["計画の管理"]。



=== 前提条件に関する情報の更新

BlueXP  ディザスタリカバリの前提条件に関する情報が更新されました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["BlueXPディザスタリカバリの前提条件"]。



== 2024年5月15日

このBlueXPディザスタリカバリリリースには、次の更新が含まれています。



=== オンプレミスからオンプレミスへのVMwareワークロードのレプリケーション

これは現在、一般提供機能としてリリースされています。以前は、機能が制限されたテクノロジプレビューでした。



=== ライセンスの更新

BlueXP  ディザスタリカバリでは、90日間の無償トライアルにサインアップするか、Amazon Marketplaceで従量課金制（PAYGO）サブスクリプションを購入するか、NetApp営業担当またはNetAppサポートサイト（NSS）から取得したNetAppライセンスファイル（NLF）であるお客様所有のライセンスを使用（BYOL）できます。

BlueXPディザスタリカバリ用のライセンスのセットアップの詳細については、を参照してください。 link:../get-started/dr-licensing.html["ライセンスをセットアップする"]。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。



== 2024年3月5日

これはBlueXPディザスタリカバリのGeneral Availabilityリリースであり、次の更新が含まれています。



=== ライセンスの更新

BlueXP  ディザスタリカバリでは、90日間の無償トライアルにサインアップするか、NetApp営業担当から入手したNetAppライセンスファイル（NLF）であるお客様所有のライセンスを使用（BYOL）できます。ライセンスのシリアル番号を使用して、BlueXPデジタルウォレットでBYOLをアクティブ化できます。BlueXPディザスタリカバリの料金は、データストアのプロビジョニング済み容量に基づいて計算されます。

BlueXPディザスタリカバリ用のライセンスのセットアップの詳細については、を参照してください。 https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["ライセンスをセットアップする"]。

すべての* BlueXPサービスのライセンス管理の詳細については、 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["すべてのBlueXPサービスのライセンスを管理します。"^]。



=== スケジュールを編集します

このリリースでは、コンプライアンステストとフェイルオーバーテストをテストするスケジュールを設定して、必要に応じて正しく動作することを確認できるようになりました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



== 2024年2月1日

このBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== ネットワークの機能拡張

このリリースでは、VMのCPU値とRAM値のサイズを変更できるようになりました。VMのネットワークDHCPまたは静的IPアドレスを選択することもできます。

* DHCP：このオプションを選択した場合は、VMのクレデンシャルを指定します。
* 静的IP：ソースVMと同じ情報または異なる情報を選択できます。ソースと同じを選択した場合は、クレデンシャルを入力する必要はありません。一方、ソースと異なる情報を使用する場合は、クレデンシャル、IPアドレス、サブネットマスク、DNS、およびゲートウェイの情報を指定できます。


詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== カスタムスクリプト

フェイルオーバー後のプロセスとして含めることができるようになりました。カスタムスクリプトを使用すると、フェイルオーバープロセスのあとにBlueXPディザスタリカバリでスクリプトを実行できます。たとえば、フェイルオーバーの完了後にすべてのデータベーストランザクションを再開するカスタムスクリプトを使用できます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["リモートサイトへのフェイルオーバー"]。



=== SnapMirror関係

レプリケーション計画の作成時にSnapMirror関係を作成できるようになりました。以前は、BlueXPのディザスタリカバリ以外で関係を作成する必要がありました。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== 整合グループ

レプリケーション計画を作成する際に、異なるボリュームや異なるSVMのVMを含めることができます。BlueXPディザスタリカバリでは、すべてのボリュームを含めて整合グループSnapshotを作成し、すべてのセカンダリサイトを更新します。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== VM電源投入遅延オプション

レプリケーション計画を作成するときに、リソースグループにVMを追加できます。リソースグループを使用すると、各VMに遅延を設定して、遅延シーケンスで電源を投入することができます。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== アプリケーションと整合性のある Snapshot コピー

アプリケーションと整合性のあるSnapshotコピーを作成するように指定できます。サービスはアプリケーションを休止し、Snapshotを作成してアプリケーションの整合性のある状態を取得します。

詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



== 2024年1月11日

今回のBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== ダッシュボードの高速化

このリリースでは、ダッシュボードから他のページの情報にすばやくアクセスできます。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。



== 2023年10月20日

今回のBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== オンプレミスのNFSベースのVMwareワークロードを保護

BlueXPディザスタリカバリを使用すると、オンプレミスのNFSベースのVMwareワークロードを、パブリッククラウドに加えてオンプレミスのNFSベースのVMware環境への災害から保護できます。BlueXPディザスタリカバリは、ディザスタリカバリ計画の完成をオーケストレーションします。


NOTE: このプレビューサービスでは、NetAppは、一般提供前にサービスの詳細、内容、スケジュールを変更する権利を留保します。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。



== 2023年9月27日

今回のBlueXPディザスタリカバリプレビューリリースには、次の更新が含まれています。



=== ダッシュボードの更新

ダッシュボードのオプションをクリックすると、情報をすばやく確認しやすくなります。また、ダッシュボードにフェイルオーバーと移行のステータスが表示されるようになりました。

を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["ダッシュボードでディザスタリカバリプランの健全性を表示する"]。



=== レプリケーション計画の更新

* * RPO *：レプリケーションプランの[データストア]セクションに、目標復旧時点（RPO）と保持数を入力できるようになりました。これは、設定された時間より前に存在する必要があるデータの量を示します。たとえば、5分に設定した場合、災害が発生してもビジネスクリティカルなニーズに影響を与えることなく、システムのデータが最大5分失われる可能性があります。
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。

* *ネットワークの機能拡張*：レプリケーション計画の仮想マシンセクションでソースとターゲットの場所間のネットワークをマッピングする際に、BlueXPディザスタリカバリでDHCPと静的IPの2つのオプションが提供されるようになりました。以前は、DHCPのみがサポートされていました。静的IPの場合は、サブネット、ゲートウェイ、およびDNSサーバを設定します。また、仮想マシンのクレデンシャルを入力できるようになりました。
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。

* *スケジュールの編集*：レプリケーションプランのスケジュールを更新できるようになりました。
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["リソースの管理"]。

* * SnapMirrorの自動化*：このリリースでレプリケーション計画を作成する際に、ソースボリュームとターゲットボリューム間のSnapMirror関係を次のいずれかの構成で定義できます。
+
** 1対1
** ファンアウトアーキテクチャで1対多
** コンシステンシグループとして多対1
** 多対多
+
を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。







== 2023年8月1日



=== BlueXP  ディザスタリカバリのプレビュー

BlueXPディザスタリカバリプレビューは、ディザスタリカバリのワークフローを自動化する、クラウドベースのディザスタリカバリサービスです。当初は、BlueXPのディザスタリカバリプレビューで、NetAppストレージを実行するオンプレミスのNFSベースのVMwareワークロードを、Amazon FSx for ONTAPを使用してAWS上のVMware Cloud（VMC）に保護できます。


NOTE: このプレビューサービスでは、NetAppは、一般提供前にサービスの詳細、内容、スケジュールを変更する権利を留保します。

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。

このリリースでは、次の更新が行われています。



=== リソースグループのブート順序の更新

ディザスタリカバリ計画またはレプリケーション計画を作成するときに、仮想マシンを機能リソースグループに追加できます。リソースグループを使用すると、依存する一連の仮想マシンを、要件を満たす論理グループにまとめることができます。たとえば、リカバリ時に実行できるブート順序をグループに含めることができます。このリリースでは、各リソースグループに1つ以上の仮想マシンを含めることができます。仮想マシンは、計画に含める順序に基づいてパワーオンされます。を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["レプリケートするアプリケーションの選択とリソースグループの割り当て"]。



=== レプリケーションの検証

ディザスタリカバリまたはレプリケーションの計画を作成し、ウィザードで繰り返しを特定し、ディザスタリカバリサイトへのレプリケーションを開始したら、30分ごとにBlueXP  ディザスタリカバリによって、計画に従ってレプリケーションが実際に実行されているかどうかが検証されます。進捗状況は[Job Monitor]ページで監視できます。を参照してください  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["アプリケーションを別のサイトにレプリケート"]。



=== レプリケーションプランで目標復旧時点（RPO）の転送スケジュールを表示

ディザスタリカバリ計画またはレプリケーション計画を作成するときは、VMを選択します。このリリースでは、データストアまたはVMに関連付けられている各ボリュームに関連付けられているSnapMirrorを確認できるようになりました。SnapMirrorスケジュールに関連付けられているRPO転送スケジュールも確認できます。RPOは、災害発生後にリカバリするのに十分なバックアップスケジュールであるかどうかを判断するのに役立ちます。を参照してください https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["レプリケーション計画の作成"]。



=== ジョブモニタの更新

[Job Monitor]ページに[Refresh]オプションが追加され、処理の最新ステータスを確認できるようになりました。を参照してください  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["ディザスタリカバリジョブを監視する"]。



== 2023年5月18日

これは、BlueXPディザスタリカバリの初版リリースです。



=== クラウドベースのディザスタリカバリサービス

BlueXPのディザスタリカバリは、ディザスタリカバリのワークフローを自動化する、クラウドベースのディザスタリカバリサービスです。当初は、BlueXPのディザスタリカバリプレビューで、NetAppストレージを実行するオンプレミスのNFSベースのVMwareワークロードを、Amazon FSx for ONTAPを使用してAWS上のVMware Cloud（VMC）に保護できます。

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["BlueXPディザスタリカバリの詳細"]。
